name: gpu-snn-glm-simulator

channels:
    - pytorch
    - nvidia
    - pyg
    - conda-forge
    - defaults

dependencies:
        - cudatoolkit=11.7
        - pip
        - python
        - pytorch-cuda=11.7
        - pytorch
        - pyg
        pip:
          - -r requirements_dev.txt