#!/bin/bash
set -e

rsync -av --exclude .git --exclude __pycache__ spiking_network ex3:~/

ssh ex3 -t 'source .bashrc && \
    echo "Running on ex3" && \
    rm *.out | true && \
    /cm/shared/apps/slurm/20.02.7/bin/sbatch -p hgx2q run.sbatch '$1' '$2' '$3' '$4' && \
    until [ -f *.out ]
    do
         sleep 0.5
    done
    tail -f *.out'
