from spikeometric.models.sa_model import SAModel
import torch
from tqdm import tqdm

class RectifiedSAM(SAModel):
    r"""
    The Rectified Synaptic Activation Model from section S.5 of the paper `"Systematic errors in connectivity inferred from activity in strongly coupled recurrent circuits" <https://www.biorxiv.org/content/10.1101/512053v1.full>`_.

    This is a Linear-Nonlinear-Poisson model that uses a rectified linear non-linearity and Poisson spiking. 
    It can be descibed as a mixture of the ThresholdSAM and the RectifiedLNP models. It uses activation as 
    state like the ThresholdSAM, but uses a rectified non-linearity and Poisson spiking like the RectifiedLNP.
    Unlike the ThresholdSAM, the RectifiedSAM is tunable.

    The input to each neuron at time :math:`t+1` is calculated as follows:
    
    .. math::
        g_i(t+1) = r \: \sum_j W_{j,i}\: s_j(t) + b_i(t+1) + f_i(t+1)
    
    where :math:`r` is the scaling of the recurrent connections, :math:`b_i` is the strength of a unifrom background input
    and :math:`f_i(t+1)` is the stimulus input to neuron :math:`i` at time :math:`t+1`.

    The response to the input is then rectified to give an expected firing rate:

    .. math::
        \mu_i(t+1) = \lambda_0[g_i(t+1)) - \theta]_+

    where :math:`\lambda_0` and :math:`\theta` are parameters of the model and :math:`[x]_+` is the rectified linear function.

    The spikes are then generated by a Poisson process with rate :math:`\mu_i(t+1)`:

    .. math::
        x_i(t+1) = \text{Pois}(\mu_i(t+1))

    Parameters
    ----------
    lambda_0 : float
        The scaling of the rectified non-linearity.
    theta : float
        The threshold of the rectified non-linearity.
    tau : float
        The time constant of the neurons.
    dt : float
        The time step of the simulation.
    r : float
        The scaling of the recurrent connections.
    b : float
        The baseline strength of the background input.
    rng : torch.Generator, optional
        The random number generator to use for the Poisson process.
    """
    def __init__(self, lambda_0: float, theta: float, T: int, tau: float, dt: float, r: float, b: float, rng=None):
        super().__init__()
        # Buffers
        self.register_buffer("dt", torch.tensor(dt, dtype=torch.float32))

        # Parameters
        self.register_parameter("lambda_0", torch.nn.Parameter(torch.tensor(lambda_0, dtype=torch.float32)))
        self.register_parameter("theta", torch.nn.Parameter(torch.tensor(theta, dtype=torch.float32)))
        self.register_parameter("tau", torch.nn.Parameter(torch.tensor(tau, dtype=torch.float32)))
        self.register_parameter("r", torch.nn.Parameter(torch.tensor(r, dtype=torch.float32)))
        self.register_parameter("b", torch.nn.Parameter(torch.tensor(b, dtype=torch.float32)))

        # RNG
        self._rng = rng if rng is not None else torch.Generator()

        self.requires_grad_(False)

    def input(self, edge_index: torch.Tensor, W: torch.Tensor, state: torch.Tensor, t=-1, stimulus_mask=False) -> torch.Tensor:
        return (
            self.r*self.synaptic_input(edge_index, W, state)
             + self.stimulus_input(t, stimulus_mask)
             + self.b
        )
    
    def non_linearity(self, input: torch.Tensor) -> torch.Tensor:
        return self.lambda_0*torch.relu(input - self.theta) * self.dt

    def emit_spikes(self, rates: torch.Tensor) -> torch.Tensor:
        return torch.poisson(rates, generator=self._rng).to(dtype=torch.uint8)